spring.application.name=school
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Avatar configuration
avatars.directory.path=./avatars

# Default logging level
logging.level.org.springframework=INFO
logging.level.ru.hogwarts.school=INFO
logging.level.org.hibernate=WARN

# Active profile (change to dev or prod as needed)
spring.profiles.active=default